# Generated by Django 5.2.8 on 2025-11-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_alter_pokemon_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='photo',
        ),
    ]
