# Generated by Django 5.2.8 on 2025-11-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_alter_pokemon_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='lan',
            new_name='lon',
        ),
    ]
