# Generated by Django 5.2.8 on 2025-11-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0023_alter_pokemon_description_alter_pokemon_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='предыдущая эволюция'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pokemon_entities', to='pokemon_entities.pokemon', verbose_name='покемон'),
        ),
    ]
