# Generated by Django 5.2.8 on 2025-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='lan',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='lat',
            field=models.FloatField(null=True),
        ),
    ]
