# Generated by Django 5.2.8 on 2025-11-22 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonentity_lan_pokemonentity_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pokemon_entities.pokemon'),
        ),
    ]
