# Generated by Django 5.2.8 on 2025-11-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_rename_lan_pokemonentity_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pokemon_entities', to='pokemon_entities.pokemon'),
        ),
    ]
